* docs/release: Updated -- Savannah uses a new uploading scheme.
formatting

diff --git a/docs/release b/docs/release
--- a/docs/release
+++ b/docs/release
@@ -7,7 +7,7 @@ How to prepare a new release
 . Update version numbers in all files where necessary (for example, do
   a grep for both `2.3.0' and `230' for release 2.3.0).
 
-. Jamfile (RefDoc): Update the `--title' option.
+. builds/unix/configure.raw: Update `version_info'.
 
 . docs/CHANGES: Document differences to last release.
 
@@ -34,44 +34,76 @@ How to prepare a new release
   except the `reference' subdirectory.   Do *not* use option `-l' from
   zip!
 
-. Run the following script  (updating `VERSION' and `version' with the
-  actual version strings)  to upload the bundles to  both Savannah and
-  SourceForge.  `gnupload' is a script taken from the automake bundle.
+  Run   the   following   script    (with   updated   `$VERSION'   and
+  `$SAVANNAH_USER'  variables) to sign and upload  the bundles to both
+  Savannah and SourceForge.  The signing code  has been taken from the
+  `gnupload' script (part of the automake bundle).
+
+    #!/bin/sh
 
     VERSION=2.3.0
-    version=230
+    SAVANNAH_USER=wl
 
-    gnupload --to savannah.nongnu.org:freetype \
-             freetype-$VERSION.tar.gz \
-             freetype-$VERSION.tar.bz2 \
-             ft$version.zip \
-             ft2demos-$VERSION.tar.gz \
-             ft2demos-$VERSION.tar.bz2 \
-             ftdmo$version.zip \
-             freetype-doc-$VERSION.tar.gz \
-             freetype-doc-$VERSION.tar.bz2 \
-             ftdoc$version.zip
+    #####################################################################
 
-    for f in freetype-$VERSION.tar.gz \
-             freetype-$VERSION.tar.gz.sig \
-             freetype-$VERSION.tar.bz2 \
-             freetype-$VERSION.tar.bz2.sig \
-             ft$version.zip \
-             ft$version.zip.sig \
-             ft2demos-$VERSION.tar.gz \
-             ft2demos-$VERSION.tar.gz.sig \
-             ft2demos-$VERSION.tar.bz2 \
-             ft2demos-$VERSION.tar.bz2.sig \
-             ftdmo$version.zip \
-             ftdmo$version.zip.sig \
-             freetype-doc-$VERSION.tar.gz \
-             freetype-doc-$VERSION.tar.gz.sig \
-             freetype-doc-$VERSION.tar.bz2 \
-             freetype-doc-$VERSION.tar.bz2.sig \
-             ftdoc$version.zip \
-             ftdoc$version.zip.sig ; do
+    GPG='/usr/bin/gpg --batch --no-tty'
+
+    version=`echo $VERSION | sed "s/\\.//g"`
+
+    UNIX_PACKAGES="freetype ft2demos freetype-doc"
+    WINDOWS_PACKAGES="ft ftdmo ftdoc"
+    UNIX_ZIP="tar.gz tar.bz2"
+    WINDOWS_ZIP="zip"
+
+    PACKAGE_LIST=
+    for i in $UNIX_PACKAGES; do
+      for j in $UNIX_ZIP; do
+        PACKAGE_LIST="$PACKAGE_LIST $i-$VERSION.$j"
+      done
+    done
+    for i in $WINDOWS_PACKAGES; do
+      for j in $WINDOWS_ZIP; do
+        PACKAGE_LIST="$PACKAGE_LIST $i$version.$j"
+      done
+    done
+
+    set -e
+    unset passphrase
+
+    PATH=/empty echo -n "Enter GPG passphrase: "
+    stty -echo
+    read -r passphrase
+    stty echo
+    echo
+
+    for f in $PACKAGE_LIST; do
+      if test ! -f $f; then
+        echo "$0: Cannot find \`$f'" 1>&2
+        exit 1
+      else
+        :
+      fi
+    done
+
+    for f in $PACKAGE_LIST; do
+      echo "Signing $f..."
+      rm -f $f.sig
+      echo $passphrase | $GPG --passphrase-fd 0 -ba -o $f.sig $f
+    done
+
+    SIGNATURE_LIST=
+    for i in $PACKAGE_LIST; do
+      SIGNATURE_LIST="$SIGNATURE_LIST $i.sig"
+    done
+
+    scp $PACKAGE_LIST $SIGNATURE_LIST \
+      $SAVANNAH_USER@dl.sv.nongnu.org:/releases/freetype/
+
+    for f in $PACKAGE_LIST $SIGNATURE_LIST; do
       ncftpput upload.sf.net /incoming $f
     done
+
+    # EOF
 
 . While files on savannah.gnu.org are automatically moved to the right
   directory, it must be done manually on SourceForge.  Do that now.
